version: "3.8"
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
    network_mode: "host"
volumes:
  cache:
    driver: local
